In [1]:
import pandas as pd

In [6]:
x = pd.read_csv("data_hdf5_cropped/shape_info.csv", index_col=1)

In [14]:
positive_slope = x.loc[x["mean_slope"] > 0]

In [8]:
patient_injuries = pd.read_csv("data/train.csv", index_col=0)

In [16]:
patients_with_injuries = list(patient_injuries.loc[patient_injuries["any_injury"] == 1].index)

In [17]:
positive_slope.loc[positive_slope["patient_id"].isin(patients_with_injuries)]

,patient_id,shape_h,shape_w,z_positions,mean_slope
series_id,,,,,
14668,15472,366,397,"[-740.197, -737.197, -734.197, -731.197, -728....",3.00
43041,34354,358,486,"[-633.8, -632.55, -631.3, -630.05, -628.8, -62...",1.25
30155,34717,316,407,"[-741.512, -738.512, -735.512, -732.512, -729....",3.00
54975,34869,312,375,"[-669.943, -666.943, -663.943, -660.943, -657....",3.00
38639,3847,350,419,"[-730.29, -727.29, -724.29, -721.29, -718.29, ...",3.00
34993,4275,332,402,"[-731.182, -728.182, -725.182, -722.182, -719....",3.00
12082,44861,346,429,"[-760.932, -757.932, -754.932, -751.932, -748....",3.00
242,46505,344,405,"[-697.143, -694.143, -691.143, -688.143, -685....",3.00
20158,48540,365,420,"[-745.977, -742.977, -739.977, -736.977, -733....",3.00
47288,56534,387,423,"[-727.002, -724.002, -721.002, -718.002, -715....",3.00
32240,65083,352,442,"[-644.531, -641.531, -638.531, -635.531, -632....",3.00